[package]
name = "kayak_ui"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = ["bevy_kayak_ui", "kayak_core", "kayak_render_macros", "kayak_font"]

[features]
default = ["bevy_renderer"]
bevy_renderer = [
    "bevy_kayak_ui",
    "kayak_core/bevy_renderer",
    "kayak_font/bevy_renderer",
    "bevy",
]

[dependencies]
bevy = { version = "0.7.0", optional = true, default-features = false }
bevy_kayak_ui = { path = "bevy_kayak_ui", optional = true }
kayak_core = { path = "kayak_core" }
kayak_font = { path = "kayak_font" }
kayak_render_macros = { path = "kayak_render_macros" }

[dev-dependencies]
bevy = { version = "0.7.0", default-features = false }
rand = { version = "0.8.4" }

[[example]]
name = "todo"
path = "examples/todo/todo.rs"

[[example]]
name = "tabs"
path = "examples/tabs/tabs.rs"
