[package]
name = "kayak_font"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bevy_renderer"]
bevy_renderer = ["bevy"]

[dependencies]
anyhow = { version = "1.0" }
# bevy = { version = "0.7.0", optional = true }
bytemuck = "1.7.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1"
unicode-segmentation = "1.9"

# Provides UAX #14 line break segmentation
xi-unicode = "0.3"

[dependencies.bevy]
version = "0.7"
optional = true
default-features = false
features = [
    "bevy_render",
    "bevy_sprite",
    "bevy_core_pipeline"
]
